name: CI

on:
  pull_request:

jobs:
  approvals:
    runs-on: ubuntu-latest
    steps:
    - name: Count approvals
      uses: actions/github-script@v4
      # if: github.event_name == 'pull_request'
      with:
        script: |
          const approvedResponse = await github.graphql(`
            query($name: String!, $owner: String!, $pull_number: Int!) {
              repository(name: $name, owner: $owner) {
                pullRequest(number: $pull_number) {
                  reviews(states: APPROVED) {
                    totalCount
                  }
                }
              }
            }
          `, {
            name: context.repo.repo,
            owner: context.repo.owner,
            pull_number: context.issue.number
          });
          const approvalsRequired = 2;
          const approvals = approvedResponse.repository.pullRequest.reviews.totalCount;
          if (approvals < approvalsRequired) {
            core.setFailed(`Needs ${approvalsRequired} approvals but only has ${approvals}`);
          } else {
            console.log(`Needs ${approvalsRequired} approvals and has ${approvals}`);
          }
