name: CI

on:
  pull_request:

jobs:
  tests:
    name: Placeholder for tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: python -m pip install --upgrade wheel PyGithub
    - name: See if need to skip CI
      run: python https://raw.githubusercontent.com/pllim/action-skip-ci/main/check_commit_message.py
